### ISSUE TITLE
"Could not open lock file"

### ISSUE THREAD

**Issue by glocalglocal** [mapi68/dnscrypt-proxy-pihole#1]
Setup: dnscrypt-proxy-pihole_2.0.44; Pi-hole v5.1.2; RPi 4B, 4GB. I am also running [log2ram](https://github.com/azlux/log2ram) 

On executing this: 

`sudo dpkg -i dnscrypt-proxy-pihole_2.0.44_armhf.deb; apt install -f -y`

I am getting this:

>(Reading database ... 118347 files and directories currently installed.)
Preparing to unpack dnscrypt-proxy-pihole_2.0.44_armhf.deb ...
Unpacking dnscrypt-proxy-pihole (2.0.44) over (2.0.44) ...
Setting up dnscrypt-proxy-pihole (2.0.44) ...
adduser: Only one or two names allowed.
dpkg: error processing package dnscrypt-proxy-pihole (--install):
 installed dnscrypt-proxy-pihole package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 dnscrypt-proxy-pihole
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?

Not sure if it is a bug or how to proceed. 

EDIT: I posted an updated, more detailed version of this [here](https://discourse.pi-hole.net/t/simple-dns-over-https-with-dnscrypt-proxy-pihole-and-raspberry-pi/35238/12).

**Comment by mapi68** [comment]
Please download new deb package.
* Fixed missing user _dnscrypt-proxy
