### ISSUE TITLE
Cloudflare tests fail when Wireguard is enabled

### ISSUE THREAD

**Issue by glocalglocal** [mapi68/dnscrypt-proxy-pihole#2]
My PiHole + dnscrypt-proxy-pihole setup works fine. When I enable Wireguard on a client device to connect to PiVPN, PiHole still does its job but I don't pass the first two tests (Secure DNS and DNSSEC) on https://www.cloudflare.com/ssl/encrypted-sni/ any more. This issue disappears when I disable Wireguard, ie when the connection is local again. I expected connections via VPN to be treated as local too. Could dnscrypt-proxy-pihole have something to do with this?

**Comment by mapi68** [comment]
`pihole reconfigure`
and add wg0

**Comment by glocalglocal** [comment]
If I read this correctly, I think you mean replace my Pi-hole IPv4 address (currently 192.168.x.x/24) with 10.x.x.x/24. I suspect that would make using VPN necessary, even when my device connects locally from home. I can't do that for other reasons. VPN should only be used only when I am away from home. Is there a way to make the setup work with both VPN and non-VPN connections? I am not sure if this a dnscrypt-proxy-pihole issue. If I sorry if it isn't.

**Comment by mapi68** [comment]
In PiHole ---> Settings ---> DNS:
1) Listen on all interfaces
2) Use DNSSEC

**Comment by glocalglocal** [comment]
With 'Listen on all interfaces' (ie option 1, not option 3: 'Listen on all interfaces, permit all origins') and DNSSEC on, without switching on WireGuard several websites like BBC News or certain images on Reddit don't even load. Thanks anyway.

**Comment by mapi68** [comment]
Can you try if it works good my raspi-info with wireguard?
https://github.com/mapi68/raspi-info

Thanks.

**Comment by glocalglocal** [comment]
raspi-info works fine here. Nice collection of info. It doesn't seem to solve my problem but good to have.
