### ISSUE TITLE
Setting up a specific DNS server

### ISSUE THREAD

**Issue by inowe** [mapi68/dnscrypt-proxy-pihole#3]
Once installed, how can I configure dnscrypt to use a specific DNS server? I can see that the dnscrypt-proxy.toml file includes several lists of servers, but I would like to use only one of them.

**Comment by mapi68** [comment]
### ONLY CLOUDFLARE 1.1.1.1 SERVER
Simply add a line to /etc/dnscrypt-proxy/dnscrypt-proxy.toml in Global Settings.
If you want to add cloudflare 1.1.1.1:
`sed -i "6 i server_names = ['cloudflare']" /etc/dnscrypt-proxy/dnscrypt-proxy.toml`

Restart services:
`systemctl restart dnscrypt-proxy*`

Check if it's all OK:
` tail /var/log/syslog; tail -f  /var/log/dnscrypt-proxy/query.log`

[Public Resolvers List](https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md)

Regards.

**Comment by inowe** [comment]
Solved, thank you for the help!
