### ISSUE TITLE
Can't resolve DNS

### ISSUE THREAD

**Issue by ar4s-eth** [mapi68/dnscrypt-proxy-pihole#4]
Hi, 

I tried using this script on my Umbrel + Pihole setup, I wasn't able to resolve any addresses and the examples listed I followed exactly.

Thank you for including the uninstall script, so that I'm able to post this now!

If you would like me to troubleshot it I will. I wouldn't know where to start though. 

Cheers

**Comment by mapi68** [comment]
Sorry but I can't check with Umbrel, I don't have specific hardware to do this...
dnscrypt-proxy-pihole is compiled for 32bit and I think that Umbrel is 64bit.
Maybe the solution is a mix of change settings in /etc/dnscrypt-proxy/dnscrypt-proxy.toml and in pihole DNS page.
Ask [here](https://community.getumbrel.com/)
