### ISSUE TITLE
New version fails to start - Bullseye

### ISSUE THREAD

**Issue by Jimbob-B** [mapi68/dnscrypt-proxy-pihole#5]
Hi,

Just updated with git clone and installed the latest deb but it refuses to start with Bullseye running on a Pi Zero 2 W. The error message shown in systemctl status is,

`Apr 17 20:50:25 pihole systemd[1]: Started DNSCrypt client proxy.`
`Apr 17 20:50:25 pihole dnscrypt-proxy[10342]: /usr/sbin/dnscrypt-proxy: /lib/arm-linux-gnueabihf/libc.so.6: version 'GLIBC_2.34' not found (required by /usr/sbin/dnscrypt-proxy)`
`Apr 17 20:50:25 pihole dnscrypt-proxy[10342]: /usr/sbin/dnscrypt-proxy: /lib/arm-linux-gnueabihf/libc.so.6: version 'GLIBC_2.32' not found (required by /usr/sbin/dnscrypt-proxy)`
`Apr 17 20:50:25 pihole systemd[1]: dnscrypt-proxy.service: Main process exited, code=exited, status=1/FAILURE`
`Apr 17 20:50:25 pihole systemd[1]: dnscrypt-proxy.service: Failed with result 'exit-code'.`

Reverted back to previous version and it's working fine. I will update at some point to bookworm but didn't know if you've depreciated bullseye support or not ... the main page suggests you haven't. I think bullseye glibc6 is only 2.31 according to the output from dpkg -s libc6.

Thanks,

Jim

**Comment by mapi68** [comment]
Hi,
I also used the Pi Zero 2 W with Bullseye, and now I've upgraded to Bookworm, but I've left the file for Bullseye in the repository.
